export const role = {
  ADMIN: [
    "Dashboard.dashboard",
    "Dashboard.title",
    "Agency.title",
    "Dashboard.manage",
    "manage.employee",
    "News.title",
    "Price.title",
    "Type.title",
    "Promotion.title",
    "Advertisement.title",
    "Shift.title",
    "Room.title",
    "UserBook.title",
    "UserBook.wait",
    "ExistingCustomers.title",
    "CustomerReject.title",
    "CheckOut.title",
    "CheckIn.title",
    "ListCustomer.title",
    "CustomerUsed.title",
    "Ameniti.title",
    "Customer",
    "FeedBack.title",
  ],
  MANAGER: [
    "Dashboard.dashboard",
    "Dashboard.title",
    "News.title",
    "Price.title",
    "Type.title",
    "Promotion.title",
    "Advertisement.title",
    "Shift.title",
    "Room.title",
    "UserBook.title",
    "UserBook.wait",
    "ExistingCustomers.title",
    "CustomerReject.title",
    "CheckOut.title",
    "CheckIn.title",
    "ListCustomer.title",
    "CustomerUsed.title",
    "Ameniti.title",
    "Customer",
    "FeedBack.title",
  ],
  EMPLOYEE: [
    "UserBook.title",
    "UserBook.wait",
    "ExistingCustomers.title",
    "CustomerReject.title",
    "CheckOut.title",
    "CheckIn.title",
    "ListCustomer.title",
    "CustomerUsed.title",
    "Customer",
  ],
};

export const roleSystem = {
  ROLE_ADMIN: "ADMIN",
  ROLE_MANAGER: "MANAGER",
  ROLE_EMPLOYEE: "EMPLOYEE",
};
